apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  revision: ${istio_label}
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
